CREATE GENERATOR GEN_CATEGORIASCLASSE_ID;

CREATE TABLE CATEGORIASCLASSE(
    CODIGO        INTEGER NOT NULL,
    DESCRICAO     VARCHAR(50) CHARACTER SET WIN1252 COLLATE WIN_PTBR,
    PRINCIPAL     CHAR(1) CHARACTER SET WIN1252 COLLATE WIN_PTBR
);

ALTER TABLE CATEGORIASCLASSE ADD CONSTRAINT PK_CATEGORIASCLASSE PRIMARY KEY (CODIGO);

CREATE OR ALTER TRIGGER CATEGORIASCLASSE_BI FOR CATEGORIASCLASSE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_categoriasclasse_id,1);
end;