CREATE GENERATOR GEN_PROFESSORES_ID;

CREATE TABLE PROFESSORES (
    CODIGO  INTEGER NOT NULL,
    MEMBRO  INTEGER,
    STATUS  INTEGER
);

ALTER TABLE PROFESSORES ADD CONSTRAINT UNQ1_PROFESSORES UNIQUE (MEMBRO);

ALTER TABLE PROFESSORES ADD CONSTRAINT PK_PROFESSORES PRIMARY KEY (CODIGO);

ALTER TABLE PROFESSORES ADD CONSTRAINT FK_PROFESSORES_1 FOREIGN KEY (MEMBRO) REFERENCES MEMBROS (FICHANUMERO);

CREATE OR ALTER TRIGGER PROFESSORES_BI FOR PROFESSORES
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_professores_id,1);
end;