CREATE GENERATOR GEN_DIARIOEBQ_ID;

CREATE TABLE DIARIOEBQ(
    CODIGO      INTEGER NOT NULL,
    CLASSE      INTEGER,
    PROFESSOR   INTEGER,
    DATA        TIMESTAMP,
    VISITANTES  INTEGER,
    BIBLIAS     INTEGER,
    REVISTAS    INTEGER,
    OFERTAS     NUMERIC(15,2),
    OBSERVACOES BLOB SUB_TYPE 1 SEGMENT SIZE 32762 CHARACTER SET WIN1252,
    USERINSERT  INTEGER,
    DATAINSERT  TIMESTAMP,
    USERUPDATE  INTEGER,
    DATAUPDATE  TIMESTAMP
);

ALTER TABLE DIARIOEBQ ADD CONSTRAINT PK_DIARIOEBQ PRIMARY KEY (CODIGO);

ALTER TABLE DIARIOEBQ ADD CONSTRAINT FK_DIARIOEBQ_1 FOREIGN KEY (CLASSE) REFERENCES CLASSES (CODIGO);

ALTER TABLE DIARIOEBQ ADD CONSTRAINT FK_DIARIOEBQ_2 FOREIGN KEY (PROFESSOR) REFERENCES PROFESSORES (CODIGO);

CREATE OR ALTER TRIGGER DIARIOEBQ_BI FOR DIARIOEBQ
ACTIVE BEFORE INSERT POSITION 0
as
begin
  if (new.codigo is null) then
    new.codigo = gen_id(gen_diarioebq_id,1);
end;